server.port: 7004
spring.application.name: route
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:postgresql://localhost/route_db
  username: postgres
  password: admin

spring.datasource.hikari.initializationFailTimeout: 60000

spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword


spring.cloud.function.definition: consumerCrud;consumerTask

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    consumerCrud-in-0:
      destination: route-crud
      group: routeCrudGroup
      consumer:
        maxAttempts: 1
    consumerTask-in-0:
      destination: route-task
      group: routeTaskGroup
    routeRevise-out-0:
      destination: route-revise
    routeFind-out-0:
      destination: route-find

spring.cloud.stream.kafka.bindings:
  consumerCrud-in-0:
    consumer:
      enableDlq: true

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

server.port: 80
spring.data.redis.host: redis
