server.port: 7002
spring.application.name: store
server.error.include-message: always

spring.jackson.deserialization.adjust-dates-to-context-time-zone: true

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:postgresql://localhost/store_db
  username: postgres
  password: admin

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

channelsIn:
  crud:
    func: consumerCrud
    bind: consumerCrud-in-0
    topic: store-crud
    group: storeCrudGroup
channelsOut:
  revise:
    bind: store-revise-out-0
    topic: store-revise

spring.cloud.function.definition: ${channelsIn.crud.func}

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    consumerCrud-in-0:
      destination: ${channelsIn.crud.topic}
      group: ${channelsIn.crud.group}
    store-revise-out-0:
      destination: ${channelsOut.revise.topic}

spring.cloud.stream.bindings.consumerCrud-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092
  replication-factor: 1


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

server.port: 80
spring.cloud.stream.kafka.binder.brokers: kafka
spring.kafka.bootstrap-servers: kafka:9092
