spring.application.name: direct-service
server.port: 7000

#spring.jackson.deserialization.adjust-dates-to-context-time-zone: true

channelsIn:
channelsOut:
  store:
    bind: store-crud-out-0
    topic: store-crud
  route:
    bind: route-crud-out-0
    topic: route-crud
  cargo:
    bind: cargo-crud-out-0
    topic: cargo-crud
  order:
    bind: order-crud-out-0
    topic: order-crud
  task:
    bind: order-task-out-0
    topic: order-task


spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    store-crud-out-0:
      destination: ${channelsOut.store.topic}
    cargo-crud-out-0:
      destination: ${channelsOut.cargo.topic}
    route-crud-out-0:
      destination: ${channelsOut.route.topic}
    order-crud-out-0:
      destination: ${channelsOut.order.topic}


spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080
spring.cloud.stream.kafka.binder.brokers: kafka

