server.port: 7004
spring.application.name: route
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:postgresql://localhost/route_db
  username: postgres
  password: admin

spring.datasource.hikari.initializationFailTimeout: 60000

spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

channelsIn:
  crud:
    func: consumerCrud
    bind: consumerCrud-in-0
    topic: route-crud
    group: routeCrudGroup
  task:
    func: consumerTask
    bind: consumerTask-in-0
    topic: route-task
    group: routeTaskGroup
channelsOut:
  revise:
    bind: routeRevise-out-0
    topic: route-revise
  find:
    bind: routeFind-out-0
    topic: route-find

spring.cloud.function.definition: ${channelsIn.crud.func},${channelsIn.task.func}

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    consumerCrud-in-0:
      destination: ${channelsIn.crud.topic}
      group: ${channelsIn.crud.group}
    consumerTask-in-0:
      destination: ${channelsIn.task.topic}
      group: ${channelsIn.task.group}
    routeRevise-out-0:
      destination: ${channelsOut.revise.topic}
    routeFind-out-0:
      destination: ${channelsOut.find.topic}

spring.cloud.stream.bindings.crudConsumer-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092
  replication-factor: 1


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

server.port: 80
spring.cloud.stream.kafka.binder.brokers: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.data.redis.host: redis
